variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  key: .gitlab-cache-tfwrapper
  paths:
    - .cache/pip

stages:
  - lint
  - test

lint:
  stage: lint
  image: python:3
  script:
    - python -V
    - pip3 install -U virtualenv tox
    - tox -e lint
  tags:
    - default

tox:
  stage: test
  image: python:3
  script:
    - python -V
    - pip3 install -U virtualenv tox
    - tox
  tags:
    - default
