repos:
        - repo: https://github.com/pre-commit/pre-commit-hooks
          rev: v4.0.1
          hooks:
                  - id: trailing-whitespace
                  - id: end-of-file-fixer
                  - id: check-added-large-files
                  - id: check-toml
                  - id: check-yaml
        - repo: https://gitlab.com/pycqa/flake8
          rev: 3.9.2
          hooks:
                  - id: flake8
        - repo: https://github.com/psf/black
          rev: 21.7b0
          hooks:
                  - id: black
        - repo: https://codeberg.org/frnmst/md-toc
          rev: 8.0.1
          hooks:
                  - id: md-toc
