[tool.black]
# FIXME: match pycodestyle's max-line-length in setup.cfg.
line-length = 88 # black's default
target-version = ['py36', 'py37', 'py38']
exclude = '''
/(
  \.git
  | \.pytest_cache
  | \.tox
  | \.venv
)/
'''
